#!/bin/bash
docker rm cs
docker build -t csi ./
docker run -it \
-u $(id -u):$(id -g) \
--gpus all \
--name cs \
-v $(pwd)/data:/home/app/data \
-v $(pwd)/out:/home/app/out \
-p 0.0.0.0:6006:6006 \
csi \
$1
