#!/bin/bash
docker rm cs_jupyter
docker build -t csi ./
docker run -it \
--gpus all \
--name cs_jupyter \
-p 0.0.0.0:8888:8888 \
csi \
jupyter lab --notebook-dir='./notebooks' --no-browser --port=8888 
