#!/bin/bash
#docker rm csj
docker run -it \
--gpus all \
--name="csj-jupyter-$(date +%s)" \
-v $(pwd):/app \
-v /media/disk2/:/data \
-p 0.0.0.0:8888:8888 \
csi \
jupyter lab --notebook-dir='./notebooks' --no-browser --ip=0.0.0.0 --port=8888 
