#!/bin/bash
#docker rm csj
docker run -it \
--ipc=host \
--gpus all \
--name="csj-runcmd-$(date +%s)" \
-v $(pwd):/app \
-v /media/disk2/:/data \
-e OMP_NUM_THREADS=4 \
csi \
python3 -m torch.distributed.launch --nproc_per_node=2  \
./pytorch-image-models/train.py  \
	/data/imagenet/2012/    \
	--val-split 'val'        \
	-b 64                   \
	--model resnet18        \
	--recovery-interval 50  \
	--sched cosine          \
	--epochs 200            \
	--lr 0.05               \
	--amp                   \
	--remode pixel          \
	--reprob 0.6            \
	--aug-splits 0          \
	--aa 'v0'               \
	--dist-bn reduce        \
	--output ./out/resnet18 | tee out.txt
